### PR TITLE
Added FreeCAD as a runtime requirement

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Checklist
* [ v] Used a fork of the feedstock to propose changes
* [ v] Bumped the build number (if the version is unchanged)
* [ x] Reset the build number to `0` (if the version changed)
* [? ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ NA] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Hi! Thanks for the interest.

There are a number of other ways to install stable freecad (0.17) which
would still work with this package as-is, and freecad+deps from conda are
really heavyweight. It could have already been up here long do, but the
beta freecad means we can now at least test it all with conda-forge deps...
But I don't think offering unasked-for, early beta software to users is a
very nice thing to do.

The plan was to wait and see until...
- freecad on conda-forge is no longer a beta release
- a future cadquery is released, not depending on freecad at all (in favor
of opencascade directly)

As the first person to reply to this point effort aside from the folks who
got it working the first time, what has your experience been like?

Thanks!

**Comment by adam-urbanczyk** [comment]
Hey, from my perspective the use case behind conda is that it handles weird binary dependencies that are not possible to be resolved by pip (i.e. FreeCAD). Or to put it differently why have a conda package at all (as opposed to pip) if it does not handle the dependencies better?

I used FreeCAD conda package in the CI of cadquery. Even if it is "beta" it does the job. I would not wait for "official" CQ2.0 based on PythonOCC, it will not come anytime soon. BTW: If you want to try out "alpha" stuff: `conda install -c cadquery cq-occ`.

**Comment by bollwyvl** [comment]
On Wed, Sep 19, 2018, 16:07 Adam Urbańczyk <notifications@github.com> wrote:

> Hey, from my perspective the use case behind conda is that it handles
> weird binary dependencies that are not possible to be resolved by pip (i.e.
> FreeCAD).
>

Sure: just trying to respect that users _might_ prefer to use an existing
install over the conda-gorge one, and not download all the stuff... Aside
from the patches to even _find_ fc when installed with conda on osx, I
haven't dug too deeply into whatever magic is being done. Is there a
runtime way to specify an fc? Would it even work? What about py2? If so,
then it would be reasonable for a user to specify it... Though likely not
very portable. if it required extra work over what you'd have to do before
this was all packaged for conda, that would be unfortunate.

If it's not really feasible to use another fc,  then we definitely should
add the hard dependency!

> Or to put it differently why have a conda package at all (as opposed to
> pip) if it does not handle the dependencies better?
>
Oh to count the ways. But I hear you. It's just this _particular_
dependency chain is both deep and still a bit tenuous... And leaving it
loosely coupled reflects that.  The extra work of specifying one more
(beta) package doesn't seem like that heavy a burden.

> I used FreeCAD conda package in the CI of cadquery. Even if it is "beta"
> it does the job. I would not wait for "official" CQ2.0 based on PythonOCC,
> it will not come anytime soon.
>
right, I also test only with the fc from conda-forge, and not system
installs. Indeed, it was the access to this ease of install that prompted
me to add cadquery in the first place!

> : If you want to try out "alpha" stuff: conda install -c cadquery cq-occ.
>

Good to know! Anyhow

**Comment by adam-urbanczyk** [comment]
I do not understand what is the problem with FC conda package and OSX (no access to OSX). You could open an issue for CQ if you feel there are problems on our side. BTW: there are ways to specify FC location (by an environment variable).

With that being said, as a conda user and CQ developer, I think that it is suboptimal that a conda package does not work out of the box. How would I, as a user, know that you need to install FC if I e.g. find the package via anaconda. Also, as already mentioned, pip covers the use case that you refer to (i.e. no heave dependencies).

**Comment by bollwyvl** [comment]
Great! Since there is a way to specify an alternate FC location, and it _would_ win over the conda one, let's go ahead and merge. Let me know if you (or any of the other CQ developers) would like to be added as feedstock maintainers!

**Comment by adam-urbanczyk** [comment]
Thanks. Yes it would be great if you could add me as a maintainer.

**Pull request merged**
